# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-21 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0002_clothes_item_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='last_worn',
        ),
    ]
