# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-22 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0004_clothes_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accessory', models.ManyToManyField(related_name='outfit_accessory', to='mycloset.Clothes')),
                ('bottom', models.ManyToManyField(related_name='outfit_bottom', to='mycloset.Clothes')),
                ('shoes', models.ManyToManyField(related_name='outfit_shoes', to='mycloset.Clothes')),
                ('top', models.ManyToManyField(related_name='outfit_top', to='mycloset.Clothes')),
            ],
        ),
    ]
