# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-24 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0006_outfit_outfit_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='accessory',
        ),
        migrations.AddField(
            model_name='outfit',
            name='accessory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outfit_accessory', to='mycloset.Clothes'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='bottom',
        ),
        migrations.AddField(
            model_name='outfit',
            name='bottom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outfit_bottom', to='mycloset.Clothes'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='shoes',
        ),
        migrations.AddField(
            model_name='outfit',
            name='shoes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outfit_shoes', to='mycloset.Clothes'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='top',
        ),
        migrations.AddField(
            model_name='outfit',
            name='top',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outfit_top', to='mycloset.Clothes'),
            preserve_default=False,
        ),
    ]
