# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-24 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0007_auto_20180524_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Chicago', max_length=255),
            preserve_default=False,
        ),
    ]
